name: Bug
description: Report a bug
title: "[BUG] "
body:
  - type: textarea
    attributes:
      label: Steps to reproduce
  - type: textarea
    attributes:
      label: Expected behavior
  - type: textarea
    attributes:
      label: Actual behavior